# Generated by Django 3.0.8 on 2020-08-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=14)),
                ('email_id', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
